### ISSUE TITLE
ISO_3166-1_alpha-2 CW (Curaçao) is missing

### ISSUE THREAD

**Issue by jorbie** [sshaw/normalize_country#4]
thx for your great work so far!
can you plz add Curaçao to your list?

```
CW:
  aliases:
  - Curacao
  alpha2: CW
  alpha3: CUW
  fifa: CUW
  ioc:
  iso_name: Curaçao
  numeric: "533"
  official: Curaçao
  short: Curaçao
emoji:

```
